### ISSUE TITLE
Suggestion: remove motion graphic from homepage

### ISSUE THREAD

**Issue by jeffpaul** [wptide/docs#20]
The motion graphic on https://wptide.org/ has given some folks motion sickness and its not providing any other value for the docs site, so as we refactor the docs on wptide.org let's go ahead and remove that motion graphic.

**Comment by valendesigns** [comment]
Where was this reported? The wave graphic is the thing everyone comments about being really cool. I would rather keep it.

**Comment by jeffpaul** [comment]
@karmatosed mind chiming in on the wave animation on wptide.org and why it may be suboptimal?

**Comment by jeffpaul** [comment]
Quick search looks like these are the related items to strip out if we wanted to remove that animation: https://github.com/wptide/docs/search?q=hero__canvas&unscoped_q=hero__canvas

**Comment by jeffpaul** [comment]
Closing this for now, we can re-open if public opinion seems to warrant removing the wave graphic.
