### ISSUE TITLE
There is a typo from homepage

### ISSUE THREAD

**Issue by bharatkambariya** [wptide/docs#24]
[https://wptide.org/#architecture-diagram](url)
I have attached the screenshot for your review
![tide-screenshot](https://user-images.githubusercontent.com/3426166/54847309-06c08900-4d04-11e9-92f5-0bf61fef9257.png)

**Comment by jankimoradiya** [comment]
I have created pull request for this issue. https://github.com/wptide/docs/pull/25

**Comment by jeffpaul** [comment]
Resolved by #25.
