### ISSUE TITLE
There is extra comma(,) in docs

### ISSUE THREAD

**Issue by nitishkaila** [wptide/docs#26]
There is extra comma in the **docs/local-development.md** file under the **Composer** section example code. It will throw error if we use the example code.

Tide URL: https://www.wptide.org/local-development#composer

I have attached screenshot for the same.
![comma](https://user-images.githubusercontent.com/33976417/54994671-cf472a80-4fea-11e9-885c-1443d2cc1c54.png)

**Comment by jeffpaul** [comment]
Resolved by #28.
