### ISSUE TITLE
There is a  typo error in others' keyword

### ISSUE THREAD

**Issue by bharatkambariya** [wptide/docs#27]
There is a typo error in the following URL: need to remove apostrophes( ' ) from the **others'** keyword.

`https://github.com/wptide/docs/blob/develop/docs/code-of-conduct.md`

I have attached the screenshot for your review.
![apostrophes](https://user-images.githubusercontent.com/3426166/54994996-b723db00-4feb-11e9-86d2-3dd76d92de0f.png)

**Comment by jeffpaul** [comment]
Related: https://github.com/ContributorCovenant/contributor_covenant/pull/661

**Comment by jeffpaul** [comment]
Upstream PR was closed/wontfix so I'm going to do the same here as there's nothing for us to update.
