### ISSUE TITLE
شركة مكافحة حشرات بالمدينة المنورة 

### ISSUE THREAD

**Issue by mhggghhj** [wptide/docs#50]
[[0544142976]افضل شركة مكافحة جميع انواع الحشرات والقضاء عليها بالمدينة المنورة إذا كنت بحاجة إلى المحافظة على صحتك والنوم فى امان وعدم إزعاج الأطفال وارهاقهم فعليك بشركة روعة المدينة لمكافحة جميع انواع الحشرات مكافحة الفلل والقصور والعمائر ومكافحة الحدائق والمصانع والمنتزهات وحقن المنازل عند البناء - تركيب طارد الحمام ومكافحة الطيور التى تتسبب في توسيخ المنازل[مكافحة النمل _ الجراد _البق  _الصراصير  _الورغ  _الفئران  _العقارب]🌺🌺🌺🌺]()[]()`**[]()**`
[]()

**Comment by jeffpaul** [comment]
I admit to not being able to read the test of this issue, but in utilizing Google Translate I see that the [title translates to](https://translate.google.com/?sl=auto&tl=en&text=%D8%B4%D8%B1%D9%83%D8%A9%20%D9%85%D9%83%D8%A7%D9%81%D8%AD%D8%A9%20%D8%AD%D8%B4%D8%B1%D8%A7%D8%AA%20%D8%A8%D8%A7%D9%84%D9%85%D8%AF%D9%8A%D9%86%D8%A9%20%D8%A7%D9%84%D9%85%D9%86%D9%88%D8%B1%D8%A9&op=translate):
> An insect control company in Medina

![Screen Shot 2021-02-15 at 8 20 42 PM](https://user-images.githubusercontent.com/2818133/108010962-af98c100-6fcb-11eb-8792-40b46a7369b9.png)


...and the [description translates to](https://translate.google.com/?sl=auto&tl=en&text=%5B0544142976%5D%D8%A7%D9%81%D8%B6%D9%84%20%D8%B4%D8%B1%D9%83%D8%A9%20%D9%85%D9%83%D8%A7%D9%81%D8%AD%D8%A9%20%D8%AC%D9%85%D9%8A%D8%B9%20%D8%A7%D9%86%D9%88%D8%A7%D8%B9%20%D8%A7%D9%84%D8%AD%D8%B4%D8%B1%D8%A7%D8%AA%20%D9%88%D8%A7%D9%84%D9%82%D8%B6%D8%A7%D8%A1%20%D8%B9%D9%84%D9%8A%D9%87%D8%A7%20%D8%A8%D8%A7%D9%84%D9%85%D8%AF%D9%8A%D9%86%D8%A9%20%D8%A7%D9%84%D9%85%D9%86%D9%88%D8%B1%D8%A9%20%D8%A5%D8%B0%D8%A7%20%D9%83%D9%86%D8%AA%20%D8%A8%D8%AD%D8%A7%D8%AC%D8%A9%20%D8%A5%D9%84%D9%89%20%D8%A7%D9%84%D9%85%D8%AD%D8%A7%D9%81%D8%B8%D8%A9%20%D8%B9%D9%84%D9%89%20%D8%B5%D8%AD%D8%AA%D9%83%20%D9%88%D8%A7%D9%84%D9%86%D9%88%D9%85%20%D9%81%D9%89%20%D8%A7%D9%85%D8%A7%D9%86%20%D9%88%D8%B9%D8%AF%D9%85%20%D8%A5%D8%B2%D8%B9%D8%A7%D8%AC%20%D8%A7%D9%84%D8%A3%D8%B7%D9%81%D8%A7%D9%84%20%D9%88%D8%A7%D8%B1%D9%87%D8%A7%D9%82%D9%87%D9%85%20%D9%81%D8%B9%D9%84%D9%8A%D9%83%20%D8%A8%D8%B4%D8%B1%D9%83%D8%A9%20%D8%B1%D9%88%D8%B9%D8%A9%20%D8%A7%D9%84%D9%85%D8%AF%D9%8A%D9%86%D8%A9%20%D9%84%D9%85%D9%83%D8%A7%D9%81%D8%AD%D8%A9%20%D8%AC%D9%85%D9%8A%D8%B9%20%D8%A7%D9%86%D9%88%D8%A7%D8%B9%20%D8%A7%D9%84%D8%AD%D8%B4%D8%B1%D8%A7%D8%AA%20%D9%85%D9%83%D8%A7%D9%81%D8%AD%D8%A9%20%D8%A7%D9%84%D9%81%D9%84%D9%84%20%D9%88%D8%A7%D9%84%D9%82%D8%B5%D9%88%D8%B1%20%D9%88%D8%A7%D9%84%D8%B9%D9%85%D8%A7%D8%A6%D8%B1%20%D9%88%D9%85%D9%83%D8%A7%D9%81%D8%AD%D8%A9%20%D8%A7%D9%84%D8%AD%D8%AF%D8%A7%D8%A6%D9%82%20%D9%88%D8%A7%D9%84%D9%85%D8%B5%D8%A7%D9%86%D8%B9%20%D9%88%D8%A7%D9%84%D9%85%D9%86%D8%AA%D8%B2%D9%87%D8%A7%D8%AA%20%D9%88%D8%AD%D9%82%D9%86%20%D8%A7%D9%84%D9%85%D9%86%D8%A7%D8%B2%D9%84%20%D8%B9%D9%86%D8%AF%20%D8%A7%D9%84%D8%A8%D9%86%D8%A7%D8%A1%20-%20%D8%AA%D8%B1%D9%83%D9%8A%D8%A8%20%D8%B7%D8%A7%D8%B1%D8%AF%20%D8%A7%D9%84%D8%AD%D9%85%D8%A7%D9%85%20%D9%88%D9%85%D9%83%D8%A7%D9%81%D8%AD%D8%A9%20%D8%A7%D9%84%D8%B7%D9%8A%D9%88%D8%B1%20%D8%A7%D9%84%D8%AA%D9%89%20%D8%AA%D8%AA%D8%B3%D8%A8%D8%A8%20%D9%81%D9%8A%20%D8%AA%D9%88%D8%B3%D9%8A%D8%AE%20%D8%A7%D9%84%D9%85%D9%86%D8%A7%D8%B2%D9%84%5B%D9%85%D9%83%D8%A7%D9%81%D8%AD%D8%A9%20%D8%A7%D9%84%D9%86%D9%85%D9%84%20_%20%D8%A7%D9%84%D8%AC%D8%B1%D8%A7%D8%AF%20_%D8%A7%D9%84%D8%A8%D9%82%20_%D8%A7%D9%84%D8%B5%D8%B1%D8%A7%D8%B5%D9%8A%D8%B1%20_%D8%A7%D9%84%D9%88%D8%B1%D8%BA%20_%D8%A7%D9%84%D9%81%D8%A6%D8%B1%D8%A7%D9%86%20_%D8%A7%D9%84%D8%B9%D9%82%D8%A7%D8%B1%D8%A8%5D%F0%9F%8C%BA%F0%9F%8C%BA%F0%9F%8C%BA%F0%9F%8C%BA**%5B%5D()**&op=translate):
> [0544142976] The best company to combat all kinds of insects and eliminate them in Madinah. If you need to maintain your health and sleep in safety and not disturb and exhaust children, you should in the city splendor company to combat all kinds of insects, control villas, palaces and buildings, combating gardens, factories, parks, and injecting homes when building - installing a repellant Pigeons and birds that cause dirty houses [ants control - locusts - bugs - cockroaches - orgas - mice - scorpions] 🌺🌺🌺🌺 ** [] () **

![Screen Shot 2021-02-15 at 8 20 58 PM](https://user-images.githubusercontent.com/2818133/108010970-b58ea200-6fcb-11eb-8143-d35b4ce42561.png)


As such, this appears to be spam so I'm closing this issue.  @mhggghhj if you have a legitimate Tide issue, please re-state your issue.
